spring:
  application:
    name: Api-gateway-in-ecommerce

  # API Gateway configs
  cloud:
    gateway:
      routes:
        - id: Order-Service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters :
            - StripPrefix=2
        - id: Inventory-Service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
              - StripPrefix=2

# Eureka configs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
