resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 3
        waitDuration : 5s

  ratelimiter:
    instances:
      inventoryRateLimiter:
        timeRefreshPeriod : 5s
        limitForPeriod: 1
        limitOutDuration : 1s